### ISSUE TITLE
Ability to run in production mode

### ISSUE THREAD

**Issue by atridgedcosta** [bigdatr/bigdatr-startr#9]
`npm run fakeproduction`

**Comment by atridgedcosta** [comment]
Also, i'm thinking that production should use pm2 by default? Thoughts?

https://github.com/Unitech/pm2

**Comment by allanhortle** [comment]
Fixed in #12 
Instead of a npm run script. I've added a `.env` that lets you edit the different environment variables that is ignored by git. This lets the developer config all aspects of the app how they would like without having config files changing left right and centre.

PM will be added in docker configs.
